In [1]:
import pip
import numpy as np
import pandas as pd
import sklearn
import tabulate
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn import preprocessing

In [25]:
song_app = pd.read_csv("../../SongApp.csv",header=-1,)

In [26]:
song_app.head()

,0,1,2,3,4,5,6,7,8,9,...,82,83,84,85,86,87,88,89,90,91
0,NaN,2001,49.94357,21.47114,73.07750,8.74861,-17.40628,-13.09905,-25.01202,-12.23257,...,13.01620,-54.40548,58.99367,15.37344,1.11144,-23.08793,68.40795,-1.82223,-27.46348,2.26327
1,0.0,2001,48.73215,18.42930,70.32679,12.94636,-10.32437,-24.83777,8.76630,-0.92019,...,5.66812,-19.68073,33.04964,42.87836,-9.90378,-32.22788,70.49388,12.04941,58.43453,26.92061
2,1.0,2001,50.95714,31.85602,55.81851,13.41693,-6.57898,-18.54940,-3.27872,-2.35035,...,3.03800,26.05866,-50.92779,10.93792,-0.07568,43.20130,-115.00698,-0.05859,39.67068,-0.66345
3,2.0,2001,48.24750,-1.89837,36.29772,2.58776,0.97170,-26.21683,5.05097,-10.34124,...,34.57337,-171.70734,-16.96705,-46.67617,-12.51516,82.58061,-72.08993,9.90558,199.62971,18.85382
4,3.0,2001,50.97020,42.20998,67.09964,8.46791,-15.85279,-16.81409,-12.48207,-9.37636,...,9.92661,-55.95724,64.92712,-17.72522,-1.49237,-7.50035,51.76631,7.88713,55.66926,28.74903

In [27]:
# clean data
df_song = song_app.dropna()
df_song.__delitem__(0)
del song_app

In [28]:
df_song.head()

,1,2,3,4,5,6,7,8,9,10,...,82,83,84,85,86,87,88,89,90,91
1,2001,48.73215,18.42930,70.32679,12.94636,-10.32437,-24.83777,8.76630,-0.92019,18.76548,...,5.66812,-19.68073,33.04964,42.87836,-9.90378,-32.22788,70.49388,12.04941,58.43453,26.92061
2,2001,50.95714,31.85602,55.81851,13.41693,-6.57898,-18.54940,-3.27872,-2.35035,16.07017,...,3.03800,26.05866,-50.92779,10.93792,-0.07568,43.20130,-115.00698,-0.05859,39.67068,-0.66345
3,2001,48.24750,-1.89837,36.29772,2.58776,0.97170,-26.21683,5.05097,-10.34124,3.55005,...,34.57337,-171.70734,-16.96705,-46.67617,-12.51516,82.58061,-72.08993,9.90558,199.62971,18.85382
4,2001,50.97020,42.20998,67.09964,8.46791,-15.85279,-16.81409,-12.48207,-9.37636,12.63699,...,9.92661,-55.95724,64.92712,-17.72522,-1.49237,-7.50035,51.76631,7.88713,55.66926,28.74903
5,2001,50.54767,0.31568,92.35066,22.38696,-25.51870,-19.04928,20.67345,-5.19943,3.63566,...,6.59753,-50.69577,26.02574,18.94430,-0.33730,6.09352,35.18381,5.00283,-11.02257,0.02263

In [29]:
df_song = df_song[df_song[1] <= 2009]
df_song = df_song[df_song[1] >= 1980]

In [30]:
df_song.reindex()
df_song.shape

(418864, 91)

In [33]:
data = df_song.sample(150000)
y_data = data.values[0:,0]

In [34]:
data.__delitem__(1)
y_data

array([ 2002.,  1998.,  2008., ...,  1997.,  2005.,  2006.])

In [35]:
x_data = data

In [36]:
x_data.head()

,2,3,4,5,6,7,8,9,10,11,...,82,83,84,85,86,87,88,89,90,91
198753,45.98743,-25.97627,18.11626,-4.05858,-21.59007,-10.54384,5.97241,-2.16012,3.45335,-3.21760,...,8.51973,34.87159,64.99269,105.35242,-3.81225,-33.45330,22.57581,6.58219,-96.67505,-7.55145
75349,43.84970,19.21972,9.02008,-4.07926,-4.49463,7.53543,2.02137,-1.04036,11.44072,3.05559,...,10.13432,-73.99854,273.97408,225.79454,8.71357,70.99330,42.75875,6.86372,-132.11441,2.33990
193943,47.28449,33.59667,9.17103,14.31394,-8.68765,-18.34031,10.54602,-26.31314,-3.10006,1.33001,...,46.76959,65.04794,-85.38718,-120.64803,2.89101,42.11870,-104.77873,11.98461,-176.09774,17.92679
7493,33.07405,10.03716,9.63472,36.29589,-2.64929,40.65245,-20.63106,-8.47286,5.72274,8.89746,...,11.97170,-81.30484,-24.07189,160.63017,-36.06157,190.60231,-58.52763,2.14061,-55.63219,9.13167
387899,42.74206,-55.46167,-3.58739,-23.35380,3.16533,13.18165,-34.00444,-1.78408,29.13675,13.37231,...,60.53166,-317.34643,390.39966,95.72200,-7.19222,44.47189,-119.83174,17.39492,-113.19745,0.54181

In [116]:
x_data.shape

(418864, 90)

In [117]:
y_data.shape

(418864,)

In [37]:
normalized_X = preprocessing.normalize(x_data)

In [39]:
# split into training and test data
X_train, X_test, y_train, y_test = train_test_split(normalized_X, y_data, test_size=0.2, random_state=42)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(120000, 90)
(30000, 90)
(120000,)
(30000,)

In [40]:
clf = RandomForestRegressor(n_jobs=5, n_estimators=40)
model = clf.fit(X_train, y_train)

In [41]:
predicted = model.predict(X_test)

In [42]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.metrics import median_absolute_error

In [43]:
def log_errors(y_test, predicted):
    mae = mean_absolute_error(y_test, predicted)
    mse = mean_squared_error(y_test, predicted, multioutput='raw_values')
    r2 = r2_score(y_test, predicted)
    medae = median_absolute_error(y_test, predicted)
    print('mae ',mae)
    print('mse ',mse)
    print('r2 score ', r2)
    print('median_ae ',medae)

In [44]:
log_errors(y_test=y_test,predicted=predicted)

mae  5.05895583333
mse  [ 40.32668402]
r2 score  0.178883236803
median_ae  4.35

In [126]:
predicted

array([ 1996.15      ,  2004.33333333,  2001.83333333, ...,  1997.11666667,
        2001.7       ,  2000.13333333])

In [78]:
predicted_round = [round(x) for x in predicted]

In [80]:
score = 0
for i in range(len(y_test)):
    if(y_test[i] in [predicted[i] -1, predicted[i] + 1]):
        score = score + 1
        print('original : ', y_test[i])
        print('predicted : ', predicted_round[i])
print('score %', score/len(y_test))
print('score ',score)

original :  1999.0
predicted :  1998.0
original :  2001.0
predicted :  2000.0
original :  2003.0
predicted :  2004.0
original :  1998.0
predicted :  1999.0
original :  2005.0
predicted :  2004.0
original :  1997.0
predicted :  1998.0
original :  2005.0
predicted :  2004.0
original :  1995.0
predicted :  1996.0
original :  2000.0
predicted :  2001.0
original :  2002.0
predicted :  2001.0
original :  2001.0
predicted :  2000.0
original :  2001.0
predicted :  2002.0
original :  2002.0
predicted :  2003.0
original :  2003.0
predicted :  2004.0
original :  2000.0
predicted :  2001.0
original :  2006.0
predicted :  2005.0
original :  1997.0
predicted :  1996.0
original :  2000.0
predicted :  1999.0
original :  2002.0
predicted :  2003.0
original :  1997.0
predicted :  1998.0
original :  2001.0
predicted :  2002.0
original :  1996.0
predicted :  1997.0
original :  2002.0
predicted :  2001.0
original :  2000.0
predicted :  1999.0
original :  2000.0
predicted :  2001.0
original :  1999.0
predicted :  1998.0
original :  2001.0
predicted :  2002.0
original :  2003.0
predicted :  2004.0
original :  2003.0
predicted :  2004.0
original :  1997.0
predicted :  1998.0
original :  2005.0
predicted :  2004.0
original :  2006.0
predicted :  2005.0
original :  2004.0
predicted :  2003.0
original :  2006.0
predicted :  2005.0
original :  2001.0
predicted :  2002.0
original :  2001.0
predicted :  2002.0
original :  1998.0
predicted :  1999.0
original :  2000.0
predicted :  1999.0
original :  2004.0
predicted :  2003.0
original :  2004.0
predicted :  2003.0
original :  2002.0
predicted :  2001.0
original :  1999.0
predicted :  1998.0
original :  2000.0
predicted :  2001.0
original :  2004.0
predicted :  2003.0
original :  2005.0
predicted :  2004.0
original :  2003.0
predicted :  2004.0
original :  2002.0
predicted :  2001.0
original :  2007.0
predicted :  2006.0
original :  1998.0
predicted :  1999.0
original :  2005.0
predicted :  2004.0
original :  1994.0
predicted :  1995.0
original :  2000.0
predicted :  1999.0
original :  2004.0
predicted :  2005.0
original :  2005.0
predicted :  2004.0
original :  1993.0
predicted :  1992.0
original :  2002.0
predicted :  2001.0
original :  2004.0
predicted :  2003.0
original :  1997.0
predicted :  1998.0
original :  2007.0
predicted :  2006.0
original :  2000.0
predicted :  2001.0
original :  2006.0
predicted :  2005.0
original :  2001.0
predicted :  2002.0
original :  2000.0
predicted :  2001.0
original :  1994.0
predicted :  1995.0
original :  2001.0
predicted :  2002.0
original :  1995.0
predicted :  1996.0
original :  2001.0
predicted :  2002.0
original :  2000.0
predicted :  1999.0
original :  2003.0
predicted :  2002.0
original :  2000.0
predicted :  2001.0
original :  2001.0
predicted :  2000.0
original :  2004.0
predicted :  2003.0
original :  2001.0
predicted :  2000.0
original :  1995.0
predicted :  1994.0
original :  2004.0
predicted :  2005.0
original :  2003.0
predicted :  2002.0
original :  2000.0
predicted :  2001.0
original :  2004.0
predicted :  2005.0
original :  1999.0
predicted :  2000.0
original :  2005.0
predicted :  2004.0
original :  2004.0
predicted :  2003.0
original :  2002.0
predicted :  2001.0
original :  2001.0
predicted :  2000.0
original :  1993.0
predicted :  1994.0
original :  2001.0
predicted :  2002.0
original :  1992.0
predicted :  1993.0
original :  2004.0
predicted :  2003.0
original :  1998.0
predicted :  1997.0
original :  1999.0
predicted :  2000.0
original :  1995.0
predicted :  1994.0
original :  2000.0
predicted :  2001.0
original :  2001.0
predicted :  2000.0
original :  2002.0
predicted :  2003.0
original :  2000.0
predicted :  2001.0
original :  2001.0
predicted :  2002.0
original :  2002.0
predicted :  2003.0
original :  2001.0
predicted :  2002.0
original :  2002.0
predicted :  2001.0
original :  1996.0
predicted :  1997.0
original :  2001.0
predicted :  2002.0
original :  2002.0
predicted :  2003.0
original :  2003.0
predicted :  2002.0
original :  1999.0
predicted :  2000.0
original :  2001.0
predicted :  2002.0
original :  2002.0
predicted :  2001.0
original :  2003.0
predicted :  2002.0
score  0.0025306180915319787
106